### ISSUE TITLE
Its possible that parallel requests to recorder can cause failure

### ISSUE THREAD

**Issue by akc42** [akc42/pi_record#5]
TypeError: Cannot read property 'stderr' of undefined
1|recorder  |     at Recorder.record (/home/alan/recorder/server/recorder.js:172:24)
1|recorder  |     at /home/alan/recorder/server/server.js:170:51
1|recorder  |     at Layer.handle [as handle_request] (/home/alan/recorder/node_modules/router/lib/layer.js:93:5)
1|recorder  |     at next (/home/alan/recorder/node_modules/router/lib/route.js:144:13)
1|recorder  |     at checkRecorder (/home/alan/recorder/server/server.js:305:7)
1|recorder  |     at Layer.handle [as handle_request] (/home/alan/recorder/node_modules/router/lib/layer.js:93:5)
1|recorder  |     at next (/home/alan/recorder/node_modules/router/lib/route.js:144:13)
1|recorder  |     at Route.dispatch (/home/alan/recorder/node_modules/router/lib/route.js:109:3)
1|recorder  |     at handle (/home/alan/recorder/node_modules/router/index.js:520:11)
1|recorder  |     at Layer.handle [as handle_request] (/home/alan/recorder/node_modules/router/lib/layer.js:93:5)

**Comment by akc42** [comment]
I think we might have been switching over volumes on one side whilst starting or stopping recording at the same time
